# Config file for pact http server. Launch with `pact -s config.yaml`

# HTTP server port
port: 8080

# directory for HTTP logs
logDir: log

mysqlConnectionString: user=root;password=root;

# verbose: provide log output
verbose: True
